sched/core: Avoid a constant logical operand warning
When SCHED_DEBUG is disabled, sched_feat evaluates to a constant,
which triggers a Clang warning:

kernel/sched/core.c:935:31: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]

The kernel developers explicitly state the way sched_feat is setup
is to take advantage of compiler options. From kernel/sched/features.h:

"Each translation unit has its own copy of sysctl_sched_features to
allow constants propagation at compile time and compiler optimization
based on features default."

Clearly, Clang doesn't optimize this like GCC does. Make both compilers
happy with a static inline function like the one that was added for
ENERGY_AWARE in http://github.com/aosp-mirror/kernel_common/commit/e496f328c87173fe188e91c6cd60197fb8e7e305.

We do lose a little bit of optimization but that is alright as it is
only in this one place.